### ISSUE TITLE
Cannot disable createschema functionality

### ISSUE THREAD

**Issue by kevingoos** [SeppPenner/SerilogSinkForPostgreSQL#23] opened 2021-01-12 13:15 UTC
So, I was implementing your library for usage in one of our programs. 
Currently our database user doesn't have permissions to create tables or schema's. 
And there is where I found a small problem.

I used the property: `needAutoCreateTable: false` to disable the creation of a new table. 
But apperently it still tries to execute a query create schema, even if it already exists.

As you can see in this error:
```
Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Serilog.Sinks.PostgreSQL.SchemaCreator.CreateSchema(NpgsqlConnection connection, String schemaName)
   at Serilog.Sinks.PostgreSQL.PostgreSqlSink.EmitBatch(IEnumerable`1 events)
```

After giving the user permissions to create schema's it works, but a better solution would be if I can disable this functionality
I found that in the class PostgreSqlSink there is already a property called: `this.isSchemaCreated = false;`, but currently there is no way to adapt this property.

**So my suggestion is to add an extra parameter to set this property, or make it dependend on the property `needAutoCreateTable`**

**Comment by SeppPenner** [comment] 2021-01-12 20:17
You're right, this was a change I did some time. Should be configurable, I prefer the solution with an extra parameter. I will check this and provide an update soon.

**Comment by SeppPenner** [comment] 2021-01-14 19:58
This is fixed in version 3.2.3. `needAutoCreateSchema` is default set to `false` now.

**Comment by VBP8501** [comment] 2021-03-02 21:21
I think this is again an issue in v3.3.0. My code works in v3.2.3 but I get the same error as Kevin in v3.3.0

**Comment by SeppPenner** [comment] 2021-03-03 19:38
Ok, this is strange. In version 3.3.0, this should be fixed. I will check this soon.

**Comment by SeppPenner** [comment] 2021-03-03 22:39
@VBP8501 I didn't really change something, but could you give version 3.3.1 a try? If it still happens, I need to check the functionality again as I have tests for that cases which don't fail.

**Comment by SeppPenner** [comment] 2021-03-03 22:43
Ok, I guess I found the issue already. I hope that I can provide a fix for tomorrow. Until then, use versions below 3.3.0.

**Comment by SeppPenner** [comment] 2021-03-04 20:55
Please give version 3.3.2 a try. I hope that the issue is fixed there.

**Comment by VBP8501** [comment] 2021-03-05 08:12
Yes version 3.3.2 seems to fix this issue. Thanks!

**Comment by SeppPenner** [comment] 2021-03-05 10:41
Ok, good :)

**Closed by SeppPenner** 2021-03-05 10:41 UTC
Labels: bug
